# Generated by Django 6.0.3 on 2026-03-08 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_category_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category',
            new_name='college',
        ),
        migrations.AlterModelOptions(
            name='college',
            options={},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='college',
        ),
    ]
