# Generated by Django 6.0.3 on 2026-04-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_product_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='department',
        ),
    ]
